"""empty message

Revision ID: 301258c64f5f
Revises: f38e31707d72
Create Date: 2021-12-31 21:37:14.486300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301258c64f5f'
down_revision = 'f38e31707d72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classe_sezione', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classe_sezione')
    )
    op.create_table('materie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_materia', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_materia')
    )
    op.create_table('orari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ora_giorno', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ora_giorno')
    )
    op.create_table('orari_materie_classi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_orario', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('id_classe', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orari_materie_classi')
    op.drop_table('orari')
    op.drop_table('materie')
    op.drop_table('classi')
    # ### end Alembic commands ###
